default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  username: bruno
  password: '[ 09 osbruno ]'

development:
  <<: *default
  database: dropdown_app_development

production:
  <<: *default
  database: dropdown_app_production
